import type { Metadata } from "next";

import { ThemeModeProvider } from "@/_metronic/partials";

export const metadata: Metadata = {
  title: "Yojna",
  description: "Generated by create next app",
  icons: 'https://www.weclocks.com/assets/img/favicon.png'
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body>
        {/* <Suspense fallback={<LayoutSplashScreen />}>
            <LayoutProvider>
              
                <AuthInit>
                  <MasterLayout>
                  <AuthProvider>
                   <ToastContainer /> */}
        {/* <LanguageProvider> */}
        
        <ThemeModeProvider>{children}</ThemeModeProvider>
        {/* </LanguageProvider> */}
        {/* </AuthProvider>
                    </MasterLayout> 
                  <MasterInit />
                </AuthInit>
              </ThemeModeProvider>
            </LayoutProvider>
        </Suspense> */}
      </body>
    </html>
  );
}
